# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MAO_mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAO_mobile

  pod 'Contentful'
  pod 'Realm'

  target 'MAO_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MAO_mobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
